name: 'Google Chat Notifier'
description: 'Send notifications to Google Chat when a Pull Request is opened'
inputs:
  webhook-url:
    description: 'Google Chat webhook URL'
    required: true
  pr-data:
    description: 'Pull Request object as JSON string'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.webhook-url }}
    - ${{ inputs.pr-data }}
