name: "SQLFluff Lint Action"
description: "Lint all SQL files under the Databases directory using SQLFluff via @yu-iskw/action-sqlfluff."
author: "4RCarteri"
inputs:
  github_token:
    description: "GitHub Token for accessing the repository"
    required: true
  src:
    description: "Directory containing SQL files"
    required: false
    default: "Databases"
runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Lint SQL files with SQLFluff
      uses: yu-iskw/action-sqlfluff@v4
      with:
        github_token: ${{ inputs.github_token }}
        sqlfluff_version: "3.3.1"
        paths: ${{ inputs.src }}
        sqlfluff_command: "lint"
    
    - name: "Show outputs (Optional)"
      shell: bash
      run: |
        echo '${{ steps.lint-sql.outputs.sqlfluff-results }}' | jq -r '.'
        echo '${{ steps.lint-sql.outputs.sqlfluff-results-rdjson }}' | jq -r '.'
