name: "SQLFluff Lint Action"
description: "Lint all SQL files under the Databases directory using SQLFluff via @yu-iskw/action-sqlfluff."
author: "4RCarteri"
inputs:
  github_token:
    description: "GitHub Token for accessing the repository"
    required: true
  sqlfluff_version:
    description: "SQLFluff version to use"
    required: false
    default: "latest"
  src:
    description: "Directory containing SQL files"
    required: false
    default: "Databases"
runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Lint SQL files with SQLFluff
      uses: yu-iskw/action-sqlfluff@v4
      with:
        github_token: ${{ inputs.github_token }}
        sqlfluff_version: ${{ inputs.sqlfluff_version }}
        src: ${{ inputs.src }}
        sqlfluff_command: "lint"
