name: 'SQLFluff Lint and Fix'
description: 'Lint and auto-fix SQL files'
inputs:
  paths:
    description: 'Paths to SQL files (default: **/*.sql)'
    required: false
    default: '**/*.sql'
  dialect:
    description: 'SQL dialect (default: ansi)'
    required: false
    default: 'ansi'
  sqlfluff_version:
    description: 'sqlfluff version (default: latest)'
    required: false
    default: 'latest'
outputs:
  lint-result:
    description: 'Result of sqlfluff lint'
runs:
  using: "composite"
  steps:
    - uses: yu-iskw/action-sqlfluff@v4
      id: lint-sql
      with:
        github_token: ${{ secrets.github_token }}
        reporter: github-pr-review
        sqlfluff_version: "3.3.1"
        sqlfluff_command: "lint" # Or "lint"
        config: "${{ github.workspace }}/.sqlfluff"
        paths: "${{ github.workspace }}/models"
    - name: "Show outputs (Optional)"
      shell: bash
      run: |
        echo '${{ steps.lint-sql.outputs.sqlfluff-results }}' | jq -r '.'
        echo '${{ steps.lint-sql.outputs.sqlfluff-results-rdjson }}' | jq -r '.'
