name: 'SQLFluff Lint and Fix'
description: 'Lint and auto-fix SQL files'
inputs:
  paths:
    description: 'Paths to SQL files (default: **/*.sql)'
    required: false
    default: '**/*.sql'
  dialect:
    description: 'SQL dialect (default: ansi)'
    required: false
    default: 'ansi'
  sqlfluff_version:
    description: 'sqlfluff version (default: latest)'
    required: false
    default: 'latest'
outputs:
  lint-result:
    description: 'Result of sqlfluff lint'
runs:
  using: "composite"
  steps:
    - name: Lint SQL files
      uses: yu-iskw/action-sqlfluff@v4
      id: lint
      with:
        command: lint
        paths: ${{ inputs.paths }}
        dialect: ${{ inputs.dialect }}
        sqlfluff-version: ${{ inputs.sqlfluff_version }}

    - name: Output lint result
      shell: bash
      run: |
        echo "${{ steps.lint.outputs.result }}"
        echo "lint-result=${{ steps.lint.outputs.result }}" >> $GITHUB_OUTPUT

    - name: Fix SQL files
      uses: yu-iskw/action-sqlfluff@v4
      with:
        command: fix
        paths: ${{ inputs.paths }}
        dialect: ${{ inputs.dialect }}
        sqlfluff-version: ${{ inputs.sqlfluff_version }}
        force: true
