name: SQL Lint and Fix

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
permissions:
  pull-requests: write
  checks: write
  contents: read

jobs:
  test-check:
    name: runner / sqlfluff (github-check)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: yu-iskw/action-sqlfluff@v5
        id: lint-sql
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          sqlfluff_version: "3.4.2"
          sqlfluff_command: "fix" # Or "lint"
          config: "${{ github.workspace }}/.sqlfluff"
          paths: "${{ github.workspace }}/Databases/**"
          level: "info"
          reviewdog_version: "v0.20.3"
          dialect: "tsql"
      - name: Apply saved changes (stash)
        run: |
          git stash list
          git stash pop || true
