name: SQL Lint and Fix

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
permissions:
  pull-requests: write
  checks: write
  contents: read

jobs:
  sql-fix-check:
    name: sqlfluff fix
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: yu-iskw/action-sqlfluff@v5
        id: fix-sql
        with:
          reporter: "github-pr-review"
          github_token: ${{ secrets.github_token }}
          sqlfluff_command: "fix"
          config: "${{ github.workspace }}/.sqlfluff"
          paths: "${{ github.workspace }}/Databases/**"
          dialect: "tsql"
          fail_on_error: "true"
          sqlfluff_version: "3.4.2"

  sql-lint-check:
    name: sqlfluff lint
    runs-on: ubuntu-latest
    needs: sql-fix-check
    steps:
      - uses: actions/checkout@v4
      - uses: yu-iskw/action-sqlfluff@v5
        id: lint-sql
        with:
          reporter: "github-pr-review"
          github_token: ${{ secrets.github_token }}
          sqlfluff_command: "lint"
          config: "${{ github.workspace }}/.sqlfluff"
          paths: "${{ github.workspace }}/Databases/**"
          dialect: "tsql"
          fail_on_error: "true"
          sqlfluff_version: "3.4.2"

