name: SQL Lint and Fix

on:
  push:
    branches:
      - main
    paths:
      - 'Databases/**/*.sql'
  pull_request:
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run SQLFluff Lint
        uses: ./sql-lint-fix
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          src: "Databases"
