name: SQL Lint and Fix

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  lint_fix_sql:
    runs-on: ubuntu-latest
    steps:
      - uses: ./sql-lint-fix
        with:
          paths: '**/*.sql'
          dialect: 'ansi'
