name: sqlfluff with reviewdog
on:
  pull_request:
jobs:
  resolve-outdated-comment:
    name: "Auto Resolve Comment"
    runs-on: ubuntu-latest
    steps:
      - uses: Ardiannn08/resolve-outdated-comment@v1.3
        with:
          token: ${{ secrets.github_token }}
          mode: "resolve"
  sql-fix-check:
    name: sqlfluff fix
    runs-on: ubuntu-latest
    needs: resolve-outdated-comment
    steps:
      - uses: actions/checkout@v4
      - uses: yu-iskw/action-sqlfluff@v5
        id: fix-sql
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          sqlfluff_version: "3.4.2"
          sqlfluff_command: "fix"
          config: "${{ github.workspace }}/.sqlfluff"
          paths: "${{ github.workspace }}/Databases"
          dialect: "tsql"
          # codes for unfixable linting violations, they will be shown on lint command because they are not fixed by sqlfluff and should be handled manually
          exclude-rules: "AL04,ST11,references"
          fail_on_error: "true"

  sql-lint-check:
    name: sqlfluff lint
    runs-on: ubuntu-latest
    needs: sql-fix-check
    # Run after fix to report unfixable issues
    if: always() 
    steps:
      - uses: actions/checkout@v4
      - uses: yu-iskw/action-sqlfluff@v5
        id: lint-sql
        with:
          github_token: ${{ secrets.github_token }}
          reporter: "github-pr-review"
          sqlfluff_version: "3.4.2"
          sqlfluff_command: "lint"
          config: "${{ github.workspace }}/.sqlfluff"
          paths: "${{ github.workspace }}/Databases"
          dialect: "tsql"
          level: "info"
          fail_on_error: "true"

