name: sqlfluff with reviewdog
on:
  pull_request:
jobs:
  resolve-outdated-comment:
    name: "Auto Resolve Comment"
    runs-on: ubuntu-latest
    steps:
      - uses: Ardiannn08/resolve-outdated-comment@v1.3
        with:
          token: ${{ secrets.github_token }}
          mode: "resolve"
  sql-fix-check:
    name: runner / sqlfluff (github-check)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: yu-iskw/action-sqlfluff@v5
        id: fix-sql
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          sqlfluff_version: "3.4.2"
          sqlfluff_command: "fix"
          config: "${{ github.workspace }}/.sqlfluff"
          paths: "${{ github.workspace }}/Databases"
          dialect: "tsql"
          fail_on_error: "true"
      - name: "Show outputs (Optional)"
        shell: bash
        run: |
          echo '${{ steps.fix-sql.outputs.sqlfluff-results }}' | jq -r '.'
          echo '${{ steps.fix-sql.outputs.sqlfluff-results-rdjson }}' | jq -r '.'

  sql-lint-check:
    name: sqlfluff lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: yu-iskw/action-sqlfluff@v5
        id: lint-sql
        with:
          github_token: ${{ secrets.github_token }}
          reporter: "github-pr-review"
          sqlfluff_version: "3.4.2"
          sqlfluff_command: "lint"
          config: "${{ github.workspace }}/.sqlfluff"
          paths: "${{ github.workspace }}/Databases"
          dialect: "tsql"
          fail_on_error: "true"
      - name: "Show outputs (Optional)"
        shell: bash
        run: |
          echo '${{ steps.lint-sql.outputs.sqlfluff-results }}' | jq -r '.'
          echo '${{ steps.lint-sql.outputs.sqlfluff-results-rdjson }}' | jq -r '.'

