name: sqlfluff with reviewdog
on:
  pull_request:
jobs:
  sql-verify:
    uses: wexinc/gf-mwd-workflows/sql-verify@v1
    with:
      paths: "${{ github.workspace }}/Databases"
      config: "${{ github.workspace }}/sql-verify/.sqlfluff"
      dialect: "tsql"
    secrets:
      github_token: ${{ secrets.GITHUB_TOKEN }}
