name: SQLFluff with Reviewdog
on:
  pull_request:
  workflow_dispatch:
jobs:
  sql-verify:
    uses: 4RCarteri/github_actions_course/.github/workflows/sql-fix-lint.yml@sql-lint
    with:
      paths: "${{ github.workspace }}/Databases"
      dialect: tsql
      config: .sqlfluff
