name: SQLFluff with Reviewdog
on:
  pull_request:
jobs:
  sql-verify:
    runs-on: ubuntu-latest
    steps:
      - name: SQLFluff Fix-Lint
        uses: wexinc/edge-workflows/sql-verify@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          paths: "${{ github.workspace }}/Databases"
          config: "${{ github.workspace }}/sql-verify/.sqlfluff"
          dialect: "tsql"
