name: SQL Lint and Fix

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
permissions:
  pull-requests: write
  checks: write
  contents: read

jobs:
  test-check:
    name: runner / sqlfluff (github-check)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: yu-iskw/action-sqlfluff@v5
        id: lint-sql
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          sqlfluff_version: "3.4.2"
          sqlfluff_command: "fix" # Or "lint"
          paths: "${{ github.workspace }}/Databases"
          level: "info"
          filter_mode: "file"
          reviewdog_version: "v0.20.2"
          dialect: "tsql"
          fail_on_error: "false"
          templater: "jinja"
      - name: "Show outputs (Optional)"
        shell: bash
        run: |
          echo '${{ steps.lint-sql.outputs.sqlfluff-results }}'
          echo '${{ steps.lint-sql.outputs.sqlfluff-results-rdjson }}'
          echo '${{ steps.lint-sql.outputs.sqlfluff-exit-code }}'
          echo '${{ steps.lint-sql.outputs.reviewdog-return-code }}'
