name: SQL Lint and Fix

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint_fix_sql:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: 4RCarteri/actions/sql-lint-fix@main
        with:
          paths: '**/*.sql'
          dialect: 'ansi'
